<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\NewsletterBundle\Repository;

use Doctrine\ORM\EntityManager;
use App\CoreBundle\Libraries\gsEntityRepository;
use App\NewsletterBundle\Entity\NewsletterEmail;

/**
 * EmailReportingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterEmailRepository extends gsEntityRepository {
      
    
  
     public function saveNews($email)
    {
               
        $modul = new NewsletterEmail();
        $modul->setEmail($email );
        $modul->setIp($_SERVER["REMOTE_ADDR"]);
        $modul->setCreatedAtValue();
        $this->save($modul);                
        
    }
}
