<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\TestimonialBundle\Repository;


use App\CoreBundle\Libraries\gsEntityRepository;
use App\TestimonialBundle\Entity\Testimonial;

/**
 * EmailReportingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialRepository extends gsEntityRepository {
      

}
