<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\CounterBundle\Repository;

use Doctrine\ORM\EntityRepository;
use App\CoreBundle\Libraries\gsEntityRepository;

/**
 * Ip2CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ip2CountryRepository extends gsEntityRepository {
      
 
}
