security:

    encoders:
#        FOS\UserBundle\Model\UserInterface: bcrypt
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_COOPERATOR:  [ROLE_COOPERATOR]
        ROLE_ADMIN:       [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_COOPERATOR, ROLE_ALLOWED_TO_SWITCH]

    providers:
        custom_provider:
            id: app_user.custom_provider

    firewalls:
        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: custom_provider
                csrf_token_generator: security.csrf.token_manager
                default_target_path:  /admin/
                use_referer:   false
            logout:
                path:   /logout
                target: /
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false   

    access_control:
        - { path: ^/_wdt/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/backend/, roles: [ROLE_ADMIN] }
        - { path: ^/page/, role: ROLE_ADMIN }

#
#        #- { path: /account.*, roles: [ROLE_USER] }
#        - { path: ^/cooperator/, roles: ROLE_COOPERATOR  }
#        - { path: ^/account/, roles: ROLE_USER }
#        - { path: '^/admin*', roles: [ROLE_ADMIN] }
#        - { path: '^/(%app_locales%)/admin', roles: ROLE_ADMIN }
#        - { path: '^/admin', role: ROLE_ADMIN , }
#        - { path: '^/backend/', roles: [ROLE_ADMIN] }
#        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }


#    acl:
#        connection: default