parameters:  
  entity.NewsletterEmail: 'App\NewsletterBundle\Entity\NewsletterEmail'  
  
services:               
    
    repo.newsletterEmail:
      class: '%entity.NewsletterEmail%'
      factory: ['@app.repo.factory', 'getRepository']
      arguments:
        - '%entity.NewsletterEmail%'
         