<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\SettingsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use App\SettingsBundle\Entity\Settings;
use App\CoreBundle\Libraries\gsEntityRepository;

/**
 * CounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends gsEntityRepository
{

    public function getByName($name)
    {
        $entity = $this->findOneBy(array("name" => $name));

        if ($entity) {
            return $entity->getValue();
        }

        return false;
    }

    public function getLang()
    {
        return $this->getByName(Settings::SET_LANG);
    }

    public function getCulture()
    {
        return $this->getByName(Settings::SET_CULTURE);
    }

    public function getCompanyName()
    {
        return $this->getByName(Settings::SET_COMPANY_NAME);
    }

    public function getFirstName()
    {
        return $this->getByName(Settings::SET_FIRST_NAME);
    }

    public function getLastName()
    {
        return $this->getByName(Settings::SET_LAST_NAME);
    }

    public function getPhone()
    {
        return $this->getByName(Settings::SET_PHONE);
    }

    public function getSlogan()
    {
        return $this->getByName(Settings::SET_SLOGAN);
    }

    public function getMainEmail()
    {
        return $this->getByName(Settings::SET_EMAIL_MAIN);
    }

    public function getEmail()
    {
        return $this->getByName(Settings::SET_EMAIL);
    }
}
