<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\PagesBundle\Repository;

use Gedmo\Translatable\Entity\Repository\TranslationRepository  as Translation;
/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetatagTranslationRepository extends Translation {

    
}
