<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\PagesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use App\CoreBundle\Libraries\gsEntityRepository;

/**
 * PageFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageFilesRepository extends gsEntityRepository {

    /**
     * @return int
     */
    public function getMaxSequence() {

        $query = $this->getEntityManager()
                ->createQuery('SELECT p FROM AppFilesBundle:File p 
                                                    ORDER BY p.sequence DESC'
        );
        $query->setMaxResults(1);

        $result = $query->getOneOrNullResult();

        if ($result)
            return ($result->getSequence() + 1);
        else
            return 1;
    }

}
