<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\PagesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Gedmo\Translatable\Entity\Repository\TranslationRepository  as Translation;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTranslationRepository extends Translation {

     public function retrivatePageBySlugAndLang($slug,$lang) {

        $query = $this->getEntityManager()
                ->createQuery('SELECT p FROM AppPagesBundle:PageTranslation p                                                   
                                            WHERE p.field =:field  
                                                       and p.content =:slug
                                                       and p.locale =:lang
                                                        
                                            
                                                
                                                    ');
        $query->setParameter("lang", $lang);
        $query->setParameter("field", 'slug');
        $query->setParameter("slug", strtolower($slug));

        return  $query->getOneOrNullResult();

    }
    
}
