<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\UserBundle\Repository;

use Doctrine\ORM\EntityManager;
use App\CoreBundle\Libraries\gsEntityRepository;
use App\UserBundle\Entity\EmailReporting as EmailReporting;

/**
 * EmailReportingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailReportingRepository extends gsEntityRepository {
          
    
    
     public function saveRaport($message,$type = EmailReporting::TYPE_DEFAULT, $error = null)
    {
        
        $from  = "";
        foreach ($message->getFrom() as $key => $value) {
            $from .= $key .", ";
        }
        
        $to  = "";
        foreach ($message->getTo() as $key => $value) {
            $to .= $key.", ";
        }
        
        $modul = new EmailReporting();
        $modul->setBody($message->getBody());
        $modul->setSubject($message->getSubject());
        $modul->setFromEmail($from );
        $modul->setToEmail($to );
        $modul->setType($type);
        $modul->setIp($_SERVER["REMOTE_ADDR"]);
        $modul->setPort($_SERVER["REMOTE_PORT"]);
     //   $modul->setHost($message->getHost());
        $modul->setCreatedAtValue();
        $modul->setErrorMessage($error);
        $this->save($modul);                
        
    }
}
