<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\UserBundle\Repository;

use App\CoreBundle\Libraries\gsEntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends gsEntityRepository
{    
      public function getList($paginator, $page = 1, $perPage = 10, $sidx = "id", $sort = "asc") {

        if (!$sidx)
            $sidx = "id";
        
        $query = $this->getEntityManager()
                ->createQuery('SELECT a FROM AppUserBundle:User a
                                            LEFT JOIN a.groups g                       
                                            WHERE a.isSuperAdmin = :IsSuperAdmin       
        ');
   
        //     $c->add(self::IS_DELETED, sfGuardUser::TYPE_DELETED, Criteria::NOT_EQUAL);        
        $query->setParameter("IsSuperAdmin", false);
                                      
        return $paginator->paginate($query,$page,$perPage,array(
             'sort_field_name'=> $sidx ,         // sort field query parameter name
             'sort_direction_name'=> $sort     // sort direction query parameter name
        ));
         
    }
}
