_newsletterEmail:
    path:  /newsletterEmailSent
    defaults: { _controller: WebNewsletterBundle:NewsletterEmail:sent }
    
_newsletterEmailShow:
    path:  /newsletterEmailShow
    defaults: { _controller: WebNewsletterBundle:NewsletterEmail:show }    