<?php
/*
 * This file is part of the Gisoft package.
 *
 * (c) Damian Ostraszewski
 *
 */
namespace App\FilesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use App\FilesBundle\Entity\Thumbnail as Thumbnail;
use Imagine\Image\ImageInterface;
use Imagine\Image\Box;
use Imagine\Image\Point;

/**
 * FilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThumbnailRepository extends EntityRepository {

    /**
     * SaveThumbnails
     *
     * @param $modFiles
     * @param $fullpath
     * @param $cropped
     * @param $original
     * @param $width
     * @param $height
     * @param $status
     * @param $webPath
     */
    public function SaveThumbnails($modFiles,$fullpath,$cropped,$original,$width,$height,$status,$webPath)
    {
        $modImgThumb = new Thumbnail();
        $modImgThumb->setFile($modFiles);
        $modImgThumb->setExtention($modFiles->getExtention());
        $modImgThumb->setTitle($modFiles->getTitle());
        $modImgThumb->setFullPath($fullpath);
        $modImgThumb->setPath($webPath);
        $modImgThumb->setCropped($cropped);
        $modImgThumb->setOriginal($original);
        $modImgThumb->setWidth($width);
        $modImgThumb->setHeight($height);        
        $modImgThumb->setStatus($status);
        
        $this->Save($modImgThumb);
    }


    /**
     * Save
     *
     * @param $object
     * @return bool|void
     */
    public function Save($object) {
          $em = $this->getEntityManager();
                  
         try{
            $em->persist($object);            
             return $em->flush();  
         }
         catch (Exception $e){
             return false;
         }
     }
       
}
